/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cube.gltf 
Author: 3DHaupt (https://sketchfab.com/dennish2010)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/placeholder-cube-4-95456ddbbade438db893e2d86a84cc29
Title: Placeholder-Cube 4
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/cube.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[0.043, -0.022, 0.009]} rotation={[-Math.PI / 2, 0, 0]} scale={0.989}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube001_0" position={[-1.222, -1.5, 1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube003_1" position={[-0.828, -1.5, 1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube005_2" position={[-0.434, -1.5, 1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube007_3" position={[-0.04, -1.5, 1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube014_4" position={[0.551, -1.5, 1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube016_5" position={[0.946, -1.5, 1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube018_6" position={[1.34, -1.5, 1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube020_7" position={[1.734, -1.5, 1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube041_8" position={[-1.29, -1.5, 1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube043_9" position={[-0.896, -1.5, 1.271]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube045_10" position={[-0.502, -1.5, 1.203]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube047_11" position={[-0.108, -1.5, 1.135]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube054_12" position={[0.483, -1.5, 1.033]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube056_13" position={[0.877, -1.5, 0.965]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube058_14" position={[1.271, -1.5, 0.896]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube060_15" position={[1.666, -1.5, 0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube081_16" position={[-1.359, -1.5, 0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube083_17" position={[-0.965, -1.5, 0.877]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube085_18" position={[-0.57, -1.5, 0.809]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube087_19" position={[-0.176, -1.5, 0.741]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube094_20" position={[0.415, -1.5, 0.639]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube096_21" position={[0.809, -1.5, 0.57]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube098_22" position={[1.203, -1.5, 0.502]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube100_23" position={[1.597, -1.5, 0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1061_24" position={[-1.529, -1.1, -0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1080_25" position={[1.427, -1.1, -0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1101_26" position={[-1.597, -1.1, -0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1120_27" position={[1.359, -1.1, -0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1141_28" position={[-1.666, -1.1, -0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1160_29" position={[1.29, -1.1, -1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1181_30" position={[-1.734, -1.1, -1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1183_31" position={[-1.34, -1.1, -1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1185_32" position={[-0.946, -1.1, -1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1187_33" position={[-0.551, -1.1, -1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1194_34" position={[0.04, -1.1, -1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1196_35" position={[0.434, -1.1, -1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1198_36" position={[0.828, -1.1, -1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1200_37" position={[1.222, -1.1, -1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube121_38" position={[-1.427, -1.5, 0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube123_39" position={[-1.033, -1.5, 0.483]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube125_40" position={[-0.639, -1.5, 0.415]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube127_41" position={[-0.244, -1.5, 0.347]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube134_42" position={[0.347, -1.5, 0.244]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube136_43" position={[0.741, -1.5, 0.176]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube138_44" position={[1.135, -1.5, 0.108]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube140_45" position={[1.529, -1.5, 0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1601_46" position={[-1.222, -0.7, 1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1603_47" position={[-0.828, -0.7, 1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1605_48" position={[-0.434, -0.7, 1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1607_49" position={[-0.04, -0.7, 1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1614_50" position={[0.551, -0.7, 1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1616_51" position={[0.946, -0.7, 1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1618_52" position={[1.34, -0.7, 1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1620_53" position={[1.734, -0.7, 1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1641_54" position={[-1.29, -0.7, 1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1660_55" position={[1.666, -0.7, 0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1681_56" position={[-1.359, -0.7, 0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1700_57" position={[1.597, -0.7, 0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1721_58" position={[-1.427, -0.7, 0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1740_59" position={[1.529, -0.7, 0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1861_60" position={[-1.529, -0.7, -0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1880_61" position={[1.427, -0.7, -0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1901_62" position={[-1.597, -0.7, -0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1920_63" position={[1.359, -0.7, -0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1941_64" position={[-1.666, -0.7, -0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1960_65" position={[1.29, -0.7, -1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1981_66" position={[-1.734, -0.7, -1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1983_67" position={[-1.34, -0.7, -1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1985_68" position={[-0.946, -0.7, -1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1987_69" position={[-0.551, -0.7, -1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1994_70" position={[0.04, -0.7, -1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1996_71" position={[0.434, -0.7, -1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube1998_72" position={[0.828, -0.7, -1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2000_73" position={[1.222, -0.7, -1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2401_74" position={[-1.222, -0.3, 1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2403_75" position={[-0.828, -0.3, 1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2405_76" position={[-0.434, -0.3, 1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2407_77" position={[-0.04, -0.3, 1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2414_78" position={[0.551, -0.3, 1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2416_79" position={[0.946, -0.3, 1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2418_80" position={[1.34, -0.3, 1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2420_81" position={[1.734, -0.3, 1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2441_82" position={[-1.29, -0.3, 1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2460_83" position={[1.666, -0.3, 0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2481_84" position={[-1.359, -0.3, 0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2500_85" position={[1.597, -0.3, 0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2521_86" position={[-1.427, -0.3, 0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2540_87" position={[1.529, -0.3, 0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube261_88" position={[-1.529, -1.5, -0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube263_89" position={[-1.135, -1.5, -0.108]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube265_90" position={[-0.741, -1.5, -0.176]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2661_91" position={[-1.529, -0.3, -0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube267_92" position={[-0.347, -1.5, -0.244]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2680_93" position={[1.427, -0.3, -0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2701_94" position={[-1.597, -0.3, -0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2720_95" position={[1.359, -0.3, -0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube274_96" position={[0.244, -1.5, -0.347]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2741_97" position={[-1.666, -0.3, -0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube276_98" position={[0.639, -1.5, -0.415]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2760_99" position={[1.29, -0.3, -1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube278_100" position={[1.033, -1.5, -0.483]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2781_101" position={[-1.734, -0.3, -1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2783_102" position={[-1.34, -0.3, -1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2785_103" position={[-0.946, -0.3, -1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2787_104" position={[-0.551, -0.3, -1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2794_105" position={[0.04, -0.3, -1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2796_106" position={[0.434, -0.3, -1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2798_107" position={[0.828, -0.3, -1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube280_108" position={[1.427, -1.5, -0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube2800_109" position={[1.222, -0.3, -1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube301_110" position={[-1.597, -1.5, -0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube303_111" position={[-1.203, -1.5, -0.502]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube305_112" position={[-0.809, -1.5, -0.57]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube307_113" position={[-0.415, -1.5, -0.639]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube314_114" position={[0.176, -1.5, -0.741]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube316_115" position={[0.57, -1.5, -0.809]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube318_116" position={[0.965, -1.5, -0.877]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube320_117" position={[1.359, -1.5, -0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube341_118" position={[-1.666, -1.5, -0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube343_119" position={[-1.271, -1.5, -0.896]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube345_120" position={[-0.877, -1.5, -0.965]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube347_121" position={[-0.483, -1.5, -1.033]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube354_122" position={[0.108, -1.5, -1.135]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube356_123" position={[0.502, -1.5, -1.203]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube358_124" position={[0.896, -1.5, -1.271]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube360_125" position={[1.29, -1.5, -1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube381_126" position={[-1.734, -1.5, -1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube383_127" position={[-1.34, -1.5, -1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube385_128" position={[-0.946, -1.5, -1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube387_129" position={[-0.551, -1.5, -1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube394_130" position={[0.04, -1.5, -1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube396_131" position={[0.434, -1.5, -1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube398_132" position={[0.828, -1.5, -1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube400_133" position={[1.222, -1.5, -1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5201_134" position={[-1.222, 0.3, 1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5203_135" position={[-0.828, 0.3, 1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5205_136" position={[-0.434, 0.3, 1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5207_137" position={[-0.04, 0.3, 1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5214_138" position={[0.551, 0.3, 1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5216_139" position={[0.946, 0.3, 1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5218_140" position={[1.34, 0.3, 1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5220_141" position={[1.734, 0.3, 1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5241_142" position={[-1.29, 0.3, 1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5260_143" position={[1.666, 0.3, 0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5281_144" position={[-1.359, 0.3, 0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5300_145" position={[1.597, 0.3, 0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5321_146" position={[-1.427, 0.3, 0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5340_147" position={[1.529, 0.3, 0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5461_148" position={[-1.529, 0.3, -0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5480_149" position={[1.427, 0.3, -0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5501_150" position={[-1.597, 0.3, -0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5520_151" position={[1.359, 0.3, -0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5541_152" position={[-1.666, 0.3, -0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5560_153" position={[1.29, 0.3, -1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5581_154" position={[-1.734, 0.3, -1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5583_155" position={[-1.34, 0.3, -1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5585_156" position={[-0.946, 0.3, -1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5587_157" position={[-0.551, 0.3, -1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_318" geometry={nodes.Object_318.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5594_158" position={[0.04, 0.3, -1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5596_159" position={[0.434, 0.3, -1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_322" geometry={nodes.Object_322.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5598_160" position={[0.828, 0.3, -1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_324" geometry={nodes.Object_324.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube5600_161" position={[1.222, 0.3, -1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_326" geometry={nodes.Object_326.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6001_162" position={[-1.222, 0.7, 1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_328" geometry={nodes.Object_328.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6003_163" position={[-0.828, 0.7, 1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_330" geometry={nodes.Object_330.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6005_164" position={[-0.434, 0.7, 1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_332" geometry={nodes.Object_332.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6007_165" position={[-0.04, 0.7, 1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_334" geometry={nodes.Object_334.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6014_166" position={[0.551, 0.7, 1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_336" geometry={nodes.Object_336.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6016_167" position={[0.946, 0.7, 1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_338" geometry={nodes.Object_338.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6018_168" position={[1.34, 0.7, 1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_340" geometry={nodes.Object_340.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6020_169" position={[1.734, 0.7, 1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_342" geometry={nodes.Object_342.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6041_170" position={[-1.29, 0.7, 1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6060_171" position={[1.666, 0.7, 0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_346" geometry={nodes.Object_346.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6081_172" position={[-1.359, 0.7, 0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_348" geometry={nodes.Object_348.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6100_173" position={[1.597, 0.7, 0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_350" geometry={nodes.Object_350.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6121_174" position={[-1.427, 0.7, 0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_352" geometry={nodes.Object_352.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6140_175" position={[1.529, 0.7, 0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_354" geometry={nodes.Object_354.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6261_176" position={[-1.529, 0.7, -0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6280_177" position={[1.427, 0.7, -0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6301_178" position={[-1.597, 0.7, -0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6320_179" position={[1.359, 0.7, -0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_362" geometry={nodes.Object_362.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6341_180" position={[-1.666, 0.7, -0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_364" geometry={nodes.Object_364.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6360_181" position={[1.29, 0.7, -1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_366" geometry={nodes.Object_366.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6381_182" position={[-1.734, 0.7, -1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6383_183" position={[-1.34, 0.7, -1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_370" geometry={nodes.Object_370.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6385_184" position={[-0.946, 0.7, -1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_372" geometry={nodes.Object_372.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6387_185" position={[-0.551, 0.7, -1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6394_186" position={[0.04, 0.7, -1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_376" geometry={nodes.Object_376.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6396_187" position={[0.434, 0.7, -1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_378" geometry={nodes.Object_378.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6398_188" position={[0.828, 0.7, -1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6400_189" position={[1.222, 0.7, -1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_382" geometry={nodes.Object_382.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6801_190" position={[-1.222, 1.1, 1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6803_191" position={[-0.828, 1.1, 1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6805_192" position={[-0.434, 1.1, 1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6807_193" position={[-0.04, 1.1, 1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_390" geometry={nodes.Object_390.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6814_194" position={[0.551, 1.1, 1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6816_195" position={[0.946, 1.1, 1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_394" geometry={nodes.Object_394.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6818_196" position={[1.34, 1.1, 1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6820_197" position={[1.734, 1.1, 1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6841_198" position={[-1.29, 1.1, 1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6860_199" position={[1.666, 1.1, 0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6881_200" position={[-1.359, 1.1, 0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6900_201" position={[1.597, 1.1, 0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_406" geometry={nodes.Object_406.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6921_202" position={[-1.427, 1.1, 0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_408" geometry={nodes.Object_408.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube6940_203" position={[1.529, 1.1, 0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7061_204" position={[-1.529, 1.1, -0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7080_205" position={[1.427, 1.1, -0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_414" geometry={nodes.Object_414.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7101_206" position={[-1.597, 1.1, -0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7120_207" position={[1.359, 1.1, -0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_418" geometry={nodes.Object_418.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7141_208" position={[-1.666, 1.1, -0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_420" geometry={nodes.Object_420.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7160_209" position={[1.29, 1.1, -1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_422" geometry={nodes.Object_422.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7181_210" position={[-1.734, 1.1, -1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_424" geometry={nodes.Object_424.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7183_211" position={[-1.34, 1.1, -1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_426" geometry={nodes.Object_426.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7185_212" position={[-0.946, 1.1, -1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_428" geometry={nodes.Object_428.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7187_213" position={[-0.551, 1.1, -1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_430" geometry={nodes.Object_430.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7194_214" position={[0.04, 1.1, -1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_432" geometry={nodes.Object_432.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7196_215" position={[0.434, 1.1, -1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_434" geometry={nodes.Object_434.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7198_216" position={[0.828, 1.1, -1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_436" geometry={nodes.Object_436.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7200_217" position={[1.222, 1.1, -1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_438" geometry={nodes.Object_438.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7601_218" position={[-1.222, 1.5, 1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_440" geometry={nodes.Object_440.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7603_219" position={[-0.828, 1.5, 1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_442" geometry={nodes.Object_442.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7605_220" position={[-0.434, 1.5, 1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_444" geometry={nodes.Object_444.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7607_221" position={[-0.04, 1.5, 1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_446" geometry={nodes.Object_446.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7614_222" position={[0.551, 1.5, 1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_448" geometry={nodes.Object_448.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7616_223" position={[0.946, 1.5, 1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_450" geometry={nodes.Object_450.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7618_224" position={[1.34, 1.5, 1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_452" geometry={nodes.Object_452.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7620_225" position={[1.734, 1.5, 1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_454" geometry={nodes.Object_454.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7641_226" position={[-1.29, 1.5, 1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_456" geometry={nodes.Object_456.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7643_227" position={[-0.896, 1.5, 1.271]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_458" geometry={nodes.Object_458.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7645_228" position={[-0.502, 1.5, 1.203]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_460" geometry={nodes.Object_460.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7647_229" position={[-0.108, 1.5, 1.135]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_462" geometry={nodes.Object_462.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7654_230" position={[0.483, 1.5, 1.033]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_464" geometry={nodes.Object_464.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7656_231" position={[0.877, 1.5, 0.965]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_466" geometry={nodes.Object_466.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7658_232" position={[1.271, 1.5, 0.896]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_468" geometry={nodes.Object_468.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7660_233" position={[1.666, 1.5, 0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_470" geometry={nodes.Object_470.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7681_234" position={[-1.359, 1.5, 0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_472" geometry={nodes.Object_472.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7683_235" position={[-0.965, 1.5, 0.877]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_474" geometry={nodes.Object_474.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7685_236" position={[-0.57, 1.5, 0.809]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_476" geometry={nodes.Object_476.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7687_237" position={[-0.176, 1.5, 0.741]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_478" geometry={nodes.Object_478.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7694_238" position={[0.415, 1.5, 0.639]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_480" geometry={nodes.Object_480.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7696_239" position={[0.809, 1.5, 0.57]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_482" geometry={nodes.Object_482.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7698_240" position={[1.203, 1.5, 0.502]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_484" geometry={nodes.Object_484.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7700_241" position={[1.597, 1.5, 0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_486" geometry={nodes.Object_486.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7721_242" position={[-1.427, 1.5, 0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_488" geometry={nodes.Object_488.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7723_243" position={[-1.033, 1.5, 0.483]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_490" geometry={nodes.Object_490.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7725_244" position={[-0.639, 1.5, 0.415]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_492" geometry={nodes.Object_492.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7727_245" position={[-0.244, 1.5, 0.347]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_494" geometry={nodes.Object_494.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7734_246" position={[0.347, 1.5, 0.244]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_496" geometry={nodes.Object_496.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7736_247" position={[0.741, 1.5, 0.176]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_498" geometry={nodes.Object_498.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7738_248" position={[1.135, 1.5, 0.108]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_500" geometry={nodes.Object_500.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7740_249" position={[1.529, 1.5, 0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_502" geometry={nodes.Object_502.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7861_250" position={[-1.529, 1.5, -0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_504" geometry={nodes.Object_504.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7863_251" position={[-1.135, 1.5, -0.108]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_506" geometry={nodes.Object_506.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7865_252" position={[-0.741, 1.5, -0.176]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_508" geometry={nodes.Object_508.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7867_253" position={[-0.347, 1.5, -0.244]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_510" geometry={nodes.Object_510.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7874_254" position={[0.244, 1.5, -0.347]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_512" geometry={nodes.Object_512.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7876_255" position={[0.639, 1.5, -0.415]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_514" geometry={nodes.Object_514.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7878_256" position={[1.033, 1.5, -0.483]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_516" geometry={nodes.Object_516.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7880_257" position={[1.427, 1.5, -0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_518" geometry={nodes.Object_518.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7901_258" position={[-1.597, 1.5, -0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_520" geometry={nodes.Object_520.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7903_259" position={[-1.203, 1.5, -0.502]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_522" geometry={nodes.Object_522.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7905_260" position={[-0.809, 1.5, -0.57]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_524" geometry={nodes.Object_524.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7907_261" position={[-0.415, 1.5, -0.639]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_526" geometry={nodes.Object_526.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7914_262" position={[0.176, 1.5, -0.741]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_528" geometry={nodes.Object_528.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7916_263" position={[0.57, 1.5, -0.809]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_530" geometry={nodes.Object_530.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7918_264" position={[0.965, 1.5, -0.877]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_532" geometry={nodes.Object_532.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7920_265" position={[1.359, 1.5, -0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_534" geometry={nodes.Object_534.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7941_266" position={[-1.666, 1.5, -0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_536" geometry={nodes.Object_536.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7943_267" position={[-1.271, 1.5, -0.896]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_538" geometry={nodes.Object_538.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7945_268" position={[-0.877, 1.5, -0.965]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_540" geometry={nodes.Object_540.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7947_269" position={[-0.483, 1.5, -1.033]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_542" geometry={nodes.Object_542.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7954_270" position={[0.108, 1.5, -1.135]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_544" geometry={nodes.Object_544.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7956_271" position={[0.502, 1.5, -1.203]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_546" geometry={nodes.Object_546.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7958_272" position={[0.896, 1.5, -1.271]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_548" geometry={nodes.Object_548.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7960_273" position={[1.29, 1.5, -1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_550" geometry={nodes.Object_550.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7981_274" position={[-1.734, 1.5, -1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_552" geometry={nodes.Object_552.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7983_275" position={[-1.34, 1.5, -1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_554" geometry={nodes.Object_554.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7985_276" position={[-0.946, 1.5, -1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_556" geometry={nodes.Object_556.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7987_277" position={[-0.551, 1.5, -1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_558" geometry={nodes.Object_558.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7994_278" position={[0.04, 1.5, -1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_560" geometry={nodes.Object_560.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7996_279" position={[0.434, 1.5, -1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_562" geometry={nodes.Object_562.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube7998_280" position={[0.828, 1.5, -1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_564" geometry={nodes.Object_564.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube8000_281" position={[1.222, 1.5, -1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_566" geometry={nodes.Object_566.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube801_282" position={[-1.222, -1.1, 1.734]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_568" geometry={nodes.Object_568.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube803_283" position={[-0.828, -1.1, 1.666]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_570" geometry={nodes.Object_570.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube805_284" position={[-0.434, -1.1, 1.597]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_572" geometry={nodes.Object_572.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube807_285" position={[-0.04, -1.1, 1.529]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_574" geometry={nodes.Object_574.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube814_286" position={[0.551, -1.1, 1.427]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_576" geometry={nodes.Object_576.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube816_287" position={[0.946, -1.1, 1.359]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_578" geometry={nodes.Object_578.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube818_288" position={[1.34, -1.1, 1.29]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_580" geometry={nodes.Object_580.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube820_289" position={[1.734, -1.1, 1.222]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_582" geometry={nodes.Object_582.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube841_290" position={[-1.29, -1.1, 1.34]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_584" geometry={nodes.Object_584.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube860_291" position={[1.666, -1.1, 0.828]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_586" geometry={nodes.Object_586.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube881_292" position={[-1.359, -1.1, 0.946]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_588" geometry={nodes.Object_588.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube900_293" position={[1.597, -1.1, 0.434]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_590" geometry={nodes.Object_590.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube921_294" position={[-1.427, -1.1, 0.551]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_592" geometry={nodes.Object_592.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cube940_295" position={[1.529, -1.1, 0.04]} rotation={[0, 0.171, 0]}>
                <mesh name="Object_594" geometry={nodes.Object_594.geometry} material={materials['Material.001']} />
              </group>
              <group name="Empty_296" rotation={[0, 0.171, 0]} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cube.gltf')
